### ISSUE TITLE
HTTP Error 500 on people route

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/elementals-06-imdb-clone#78]
`http://www.lanayru.me/people/54` (Keanu Reeves) causes:

![screen shot 2018-03-12 at 08 48 29](https://user-images.githubusercontent.com/343422/37271227-3e201320-25d2-11e8-9c6c-9958f72db1ff.png)

**Comment by axeberg** [comment]
This doesn't even have a route in the web.php definition so I'm closing this...
