### ISSUE TITLE
Admin CRUD TV Shows

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/elementals-06-imdb-clone#79]
Typo in the name of the controller. The route `/admin/tvshows` is looking for `TvShowCrudController`:

https://github.com/chas-academy/elementals-06-imdb-clone/blob/master/routes/admin.php#L6

But your controller is named `TvshowCrudController.php` instead of `TvShowCrudController.php` (see here):

https://github.com/chas-academy/elementals-06-imdb-clone/blob/master/app/Http/Controllers/Admin/TvshowCrudController.php

Which causes this error to happen:

![screen shot 2018-03-12 at 09 08 50](https://user-images.githubusercontent.com/343422/37271959-5e1c2620-25d5-11e8-8024-d924ca213f75.png)

**Comment by axeberg** [comment]
@joakimunge & @zavham I've fixed this in [feature/admin-crud-tvshows-and-genres](https://github.com/chas-academy/elementals-06-imdb-clone/tree/feature/admin-crud-tvshows-and-genres)

@zavham Is working on CRUD for Episodes and Genres in that branch as well and then that should be ready for a PR.

**Comment by joakimunge** [comment]
@axelolsson Thank you for the update.
@zavham Please set up a PR as soon as you are done. Need to be merged before June 11.
