### ISSUE TITLE
Admin CRUD for seasons and episodes

### ISSUE THREAD

**Issue by axeberg** [chas-academy/elementals-06-imdb-clone#80]
All the seasons edit action button gets the following URL: `http://www.lanayru.me/admin/season//edit`

Which causes:

![screen shot 2018-03-12 at 09 12 59](https://user-images.githubusercontent.com/343422/37272021-967a72b0-25d5-11e8-817d-aa54650c7e0e.png)

Furthermore I'm having a hard time figuring out what I'm actually able to CRUD for seasons - it seems to me it's not implemented at all?

**Comment by zavham** [comment]
@axelolsson,  Issues are fixed.
